services:
  customersegmentator:
    image: customersegmentator
    build:
      context: .
      dockerfile: CustomerSegmentator/Dockerfile
      ports:
            - 80:80
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: CustomerSegmentator
    volumes:
      - ./data:/var/lib/postgresql/data
